import { CharacterXPRPG, FamiliarXPRPG, HazardXPRPG, LootXPRPG, NPCXPRPG, PartyXPRPG, VehicleXPRPG } from "@actor";
import { SenseAcuity, SenseType } from "@actor/creature/sense";
import { Alignment } from "@actor/creature/types";
import { ActorType } from "@actor/data";
import {
    ActionItemXPRPG,
    AncestryXPRPG,
    ArmorXPRPG,
    BackgroundXPRPG,
    BookXPRPG,
    ClassXPRPG,
    ConditionXPRPG,
    ConsumableXPRPG,
    ContainerXPRPG,
    DeityXPRPG,
    EffectXPRPG,
    EquipmentXPRPG,
    FeatXPRPG,
    HeritageXPRPG,
    KitXPRPG,
    LoreXPRPG,
    MeleeXPRPG,
    SpellcastingEntryXPRPG,
    SpellXPRPG,
    TreasureXPRPG,
    WeaponXPRPG,
} from "@item";
import { AfflictionXPRPG } from "@item/affliction/document";
import { ConditionSlug } from "@item/condition/data";
import { RANGE_TRAITS } from "@item/data/values";
import { DeityDomain } from "@item/deity/types";
import { FeatType } from "@item/feat/data";
import { WEAPON_PROPERTY_RUNES } from "@item/physical/runes";
import { PreciousMaterialGrade } from "@item/physical/types";
import {
    BaseWeaponType,
    MeleeWeaponGroup,
    WeaponGroup,
    WeaponPropertyRuneType,
    WeaponReloadTime,
} from "@item/weapon/types";
import { Size } from "@module/data";
import { JournalSheetXPRPG } from "@module/journal-entry/sheet";
import { sluggify } from "@util";
import enJSON from "../../../static/lang/en.json";
import { damageCategories, damageRollFlavors, damageTypes, materialDamageEffects } from "./damage";
import { immunityTypes, resistanceTypes, weaknessTypes } from "./iwr";
import {
    actionTraits,
    alignmentTraits,
    ancestryItemTraits,
    ancestryTraits,
    armorTraits,
    classTraits,
    consumableTraits,
    creatureTraits,
    damageTraits,
    equipmentTraits,
    featTraits,
    hazardTraits,
    magicSchools,
    magicTraditions,
    npcAttackTraits,
    otherArmorTags,
    otherConsumableTags,
    otherWeaponTags,
    preciousMaterials,
    spellOtherTraits,
    spellTraits,
    vehicleTraits,
    weaponTraits,
} from "./traits";

export type StatusEffectIconTheme = "default" | "blackWhite";

const actorTypes: Record<ActorType, string> = {
    character: "ACTOR.TypeCharacter",
    familiar: "ACTOR.TypeFamiliar",
    hazard: "ACTOR.TypeHazard",
    loot: "ACTOR.TypeLoot",
    npc: "ACTOR.TypeNpc",
    party: "Actor.TypeParty",
    vehicle: "ACTOR.TypeVehicle",
};

// Senses
const senses: Record<SenseType, string> = {
    darkvision: "XPRPG.Actor.Creature.Sense.Type.Darkvision",
    echolocation: "XPRPG.Actor.Creature.Sense.Type.Echolocation",
    greaterDarkvision: "XPRPG.Actor.Creature.Sense.Type.GreaterDarkvision",
    lifesense: "XPRPG.Actor.Creature.Sense.Type.Lifesense",
    lowLightVision: "XPRPG.Actor.Creature.Sense.Type.LowLightVision",
    motionsense: "XPRPG.Actor.Creature.Sense.Type.Motionsense",
    scent: "XPRPG.Actor.Creature.Sense.Type.Scent",
    seeInvisibility: "XPRPG.Actor.Creature.Sense.Type.SeeInvisibility",
    spiritsense: "XPRPG.Actor.Creature.Sense.Type.Spiritsense",
    tremorsense: "XPRPG.Actor.Creature.Sense.Type.Tremorsense",
    wavesense: "XPRPG.Actor.Creature.Sense.Type.Wavesense",
};

// Sense acuity
const senseAcuity: Record<SenseAcuity, string> = {
    imprecise: "XPRPG.Actor.Creature.Sense.Acuity.Imprecise",
    precise: "XPRPG.Actor.Creature.Sense.Acuity.Precise",
    vague: "XPRPG.Actor.Creature.Sense.Acuity.Vague",
};

const weaponPropertyRunes = {
    ...Object.entries(WEAPON_PROPERTY_RUNES).reduce((accumulated, [slug, rune]) => {
        return { ...accumulated, [slug]: rune.name };
    }, {} as Record<WeaponPropertyRuneType, string>),
};

/** Non-detection- and attitude- related conditions added to the Token HUD */
const tokenHUDConditions = {
    blinded: "XPRPG.ConditionTypeBlinded",
    broken: "XPRPG.ConditionTypeBroken",
    clumsy: "XPRPG.ConditionTypeClumsy",
    concealed: "XPRPG.ConditionTypeConcealed",
    confused: "XPRPG.ConditionTypeConfused",
    controlled: "XPRPG.ConditionTypeControlled",
    dazzled: "XPRPG.ConditionTypeDazzled",
    deafened: "XPRPG.ConditionTypeDeafened",
    doomed: "XPRPG.ConditionTypeDoomed",
    drained: "XPRPG.ConditionTypeDrained",
    dying: "XPRPG.ConditionTypeDying",
    encumbered: "XPRPG.ConditionTypeEncumbered",
    enfeebled: "XPRPG.ConditionTypeEnfeebled",
    fascinated: "XPRPG.ConditionTypeFascinated",
    fatigued: "XPRPG.ConditionTypeFatigued",
    "flat-footed": "XPRPG.ConditionTypeFlatFooted",
    fleeing: "XPRPG.ConditionTypeFleeing",
    frightened: "XPRPG.ConditionTypeFrightened",
    grabbed: "XPRPG.ConditionTypeGrabbed",
    immobilized: "XPRPG.ConditionTypeImmobilized",
    invisible: "XPRPG.ConditionTypeInvisible",
    paralyzed: "XPRPG.ConditionTypeParalyzed",
    "persistent-damage": "XPRPG.ConditionTypePersistent",
    petrified: "XPRPG.ConditionTypePetrified",
    prone: "XPRPG.ConditionTypeProne",
    quickened: "XPRPG.ConditionTypeQuickened",
    restrained: "XPRPG.ConditionTypeRestrained",
    sickened: "XPRPG.ConditionTypeSickened",
    slowed: "XPRPG.ConditionTypeSlowed",
    stunned: "XPRPG.ConditionTypeStunned",
    stupefied: "XPRPG.ConditionTypeStupefied",
    unconscious: "XPRPG.ConditionTypeUnconscious",
    undetected: "XPRPG.ConditionTypeUndetected",
    wounded: "XPRPG.ConditionTypeWounded",
};

const conditionTypes: Record<ConditionSlug, string> = {
    ...tokenHUDConditions,
    friendly: "XPRPG.ConditionTypeFriendly",
    helpful: "XPRPG.ConditionTypeHelpful",
    hidden: "XPRPG.ConditionTypeHidden",
    hostile: "XPRPG.ConditionTypeHostile",
    indifferent: "XPRPG.ConditionTypeIndifferent",
    observed: "XPRPG.ConditionTypeObserved",
    unfriendly: "XPRPG.ConditionTypeUnfriendly",
    unnoticed: "XPRPG.ConditionTypeUnnoticed",
};

const weaponCategories = {
    simple: "XPRPG.WeaponTypeSimple",
    martial: "XPRPG.WeaponTypeMartial",
    advanced: "XPRPG.WeaponTypeAdvanced",
    unarmed: "XPRPG.WeaponTypeUnarmed",
};

const baseWeaponTypes = Object.keys(enJSON.XPRPG.Weapon.Base).reduce(
    (map, slug) => ({
        ...map,
        [slug]: `XPRPG.Weapon.Base.${slug}`,
    }),
    {} as Record<BaseWeaponType, string>
);

/** Base weapon types that are considered equivalent for all rules purposes */
const equivalentWeapons = {
    "composite-longbow": "longbow",
    "composite-shortbow": "shortbow",
    "big-boom-gun": "hand-cannon",
    "spoon-gun": "hand-cannon",
} as const;

const rangeDescriptions = RANGE_TRAITS.reduce(
    (descriptions, trait) => mergeObject(descriptions, { [trait]: "XPRPG.TraitDescriptionRange" }),
    {} as Record<(typeof RANGE_TRAITS)[number], string>
);

const preciousMaterialDescriptions = {
    abysium: "XPRPG.PreciousMaterialAbysiumDescription",
    adamantine: "XPRPG.PreciousMaterialAdamantineDescription",
    "cold-iron": "XPRPG.PreciousMaterialColdIronDescription",
    darkwood: "XPRPG.PreciousMaterialDarkwoodDescription",
    djezet: "XPRPG.PreciousMaterialDjezetDescription",
    dragonhide: "XPRPG.PreciousMaterialDragonhideDescription",
    "grisantian-pelt": "XPRPG.PreciousMaterialGrisantianPeltDescription",
    inubrix: "XPRPG.PreciousMaterialInubrixDescription",
    mithral: "XPRPG.PreciousMaterialMithralDescription",
    noqual: "XPRPG.PreciousMaterialNoqualDescription",
    orichalcum: "XPRPG.PreciousMaterialOrichalcumDescription",
    siccatite: "XPRPG.PreciousMaterialSiccatiteDescription",
    silver: "XPRPG.PreciousMaterialSilverDescription",
    "sisterstone-dusk": "XPRPG.PreciousMaterialSisterstoneDescription",
    "sisterstone-scarlet": "XPRPG.PreciousMaterialSisterstoneDescription",
    "sovereign-steel": "XPRPG.PreciousMaterialSovereignSteelDescription",
    warpglass: "XPRPG.PreciousMaterialWarpglassDescription",
};

const traitsDescriptions = {
    aasimar: "XPRPG.TraitDescriptionAasimar",
    aberration: "XPRPG.TraitDescriptionAberration",
    abjuration: "XPRPG.TraitDescriptionAbjuration",
    acid: "XPRPG.TraitDescriptionAcid",
    additive0: "XPRPG.TraitDescriptionAdditive",
    additive1: "XPRPG.TraitDescriptionAdditive",
    additive2: "XPRPG.TraitDescriptionAdditive",
    additive3: "XPRPG.TraitDescriptionAdditive",
    adjusted: "XPRPG.TraitDescriptionAdjusted",
    adjustment: "XPRPG.TraitDescriptionAdjustment",
    aeon: "XPRPG.TraitDescriptionAeon",
    aesir: "XPRPG.TraitDescriptionAesir",
    aftermath: "XPRPG.TraitDescriptionAftermath",
    agathion: "XPRPG.TraitDescriptionAgathion",
    agile: "XPRPG.TraitDescriptionAgile",
    air: "XPRPG.TraitDescriptionAir",
    alchemical: "XPRPG.TraitDescriptionAlchemical",
    alchemist: "XPRPG.TraitDescriptionAlchemist",
    amphibious: "XPRPG.TraitDescriptionAmphibious",
    anadi: "XPRPG.TraitDescriptionAnadi",
    android: "XPRPG.TraitDescriptionAndroid",
    apex: "XPRPG.TraitDescriptionApex",
    aphorite: "XPRPG.TraitDescriptionAphorite",
    aquadynamic: "XPRPG.TraitDescriptionAquadynamic",
    arcane: "XPRPG.TraitDescriptionArcane",
    archetype: "XPRPG.TraitDescriptionArchetype",
    artifact: "XPRPG.TraitDescriptionArtifact",
    attached: "XPRPG.TraitDescriptionAttached",
    "attached-to-crossbow-or-firearm": "XPRPG.TraitDescriptionAttached",
    "attached-to-shield": "XPRPG.TraitDescriptionAttached",
    attack: "XPRPG.TraitDescriptionAttack",
    auditory: "XPRPG.TraitDescriptionAuditory",
    aura: "XPRPG.TraitDescriptionAura",
    automaton: "XPRPG.TraitDescriptionAutomaton",
    azarketi: "XPRPG.TraitDescriptionAzarketi",
    backstabber: "XPRPG.TraitDescriptionBackstabber",
    backswing: "XPRPG.TraitDescriptionBackswing",
    barbarian: "XPRPG.TraitDescriptionBarbarian",
    bard: "XPRPG.TraitDescriptionBard",
    beastkin: "XPRPG.TraitDescriptionBeastkin",
    bomb: "XPRPG.TraitDescriptionBomb",
    brace: "XPRPG.TraitDescriptionBrace",
    brutal: "XPRPG.TraitDescriptionBrutal",
    bulwark: "XPRPG.TraitDescriptionBulwark",
    cantrip: "XPRPG.TraitDescriptionCantrip",
    "capacity-2": "XPRPG.TraitDescriptionCapacity",
    "capacity-3": "XPRPG.TraitDescriptionCapacity",
    "capacity-4": "XPRPG.TraitDescriptionCapacity",
    "capacity-5": "XPRPG.TraitDescriptionCapacity",
    catalyst: "XPRPG.TraitDescriptionCatalyst",
    catfolk: "XPRPG.TraitDescriptionCatfolk",
    champion: "XPRPG.TraitDescriptionChampion",
    changeling: "XPRPG.TraitDescriptionChangeling",
    chaotic: "XPRPG.TraitDescriptionChaotic",
    class: "XPRPG.TraitDescriptionClass",
    cleric: "XPRPG.TraitDescriptionCleric",
    climbing: "XPRPG.TraitDescriptionClimbing",
    clockwork: "XPRPG.TraitDescriptionClockwork",
    cobbled: "XPRPG.TraitDescriptionCobbled",
    coda: "XPRPG.TraitDescriptionCoda",
    cold: "XPRPG.TraitDescriptionCold",
    combination: "XPRPG.TraitDescriptionCombination",
    comfort: "XPRPG.TraitDescriptionComfort",
    common: "XPRPG.TraitDescriptionCommon",
    companion: "XPRPG.TraitDescriptionCompanion",
    complex: "XPRPG.TraitDescriptionComplex",
    composition: "XPRPG.TraitDescriptionComposition",
    concealable: "XPRPG.TraitDescriptionConcealable",
    concentrate: "XPRPG.TraitDescriptionConcentrate",
    concussive: "XPRPG.TraitDescriptionConcussive",
    conjuration: "XPRPG.TraitDescriptionConjuration",
    conrasu: "XPRPG.TraitDescriptionConrasu",
    consecration: "XPRPG.TraitDescriptionConsecration",
    consumable: "XPRPG.TraitDescriptionConsumable",
    contact: "XPRPG.TraitDescriptionContact",
    contingency: "XPRPG.TraitDescriptionContingency",
    contract: "XPRPG.TraitDescriptionContract",
    "critical-fusion": "XPRPG.TraitDescriptionCriticalFusion",
    curse: "XPRPG.TraitDescriptionCurse",
    cursebound: "XPRPG.TraitDescriptionCursebound",
    cursed: "XPRPG.TraitDescriptionCursed",
    darkness: "XPRPG.TraitDescriptionDarkness",
    darvakka: "XPRPG.TraitDescriptionDarvakka",
    "deadly-2d10": "XPRPG.TraitDescriptionDeadly",
    "deadly-2d12": "XPRPG.TraitDescriptionDeadly",
    "deadly-2d8": "XPRPG.TraitDescriptionDeadly",
    "deadly-3d10": "XPRPG.TraitDescriptionDeadly",
    "deadly-3d12": "XPRPG.TraitDescriptionDeadly",
    "deadly-3d8": "XPRPG.TraitDescriptionDeadly",
    "deadly-4d10": "XPRPG.TraitDescriptionDeadly",
    "deadly-4d12": "XPRPG.TraitDescriptionDeadly",
    "deadly-4d8": "XPRPG.TraitDescriptionDeadly",
    "deadly-d10": "XPRPG.TraitDescriptionDeadly",
    "deadly-d12": "XPRPG.TraitDescriptionDeadly",
    "deadly-d6": "XPRPG.TraitDescriptionDeadly",
    "deadly-d8": "XPRPG.TraitDescriptionDeadly",
    death: "XPRPG.TraitDescriptionDeath",
    "deflecting-bludgeoning": "XPRPG.TraitDescriptionDeflecting",
    "deflecting-physical-ranged": "XPRPG.TraitDescriptionDeflecting",
    "deflecting-slashing": "XPRPG.TraitDescriptionDeflecting",
    dedication: "XPRPG.TraitDescriptionDedication",
    detection: "XPRPG.TraitDescriptionDetection",
    deviant: "XPRPG.TraitDescriptionDeviant",
    dhampir: "XPRPG.TraitDescriptionDhampir",
    disarm: "XPRPG.TraitDescriptionDisarm",
    disease: "XPRPG.TraitDescriptionDisease",
    divination: "XPRPG.TraitDescriptionDivination",
    divine: "XPRPG.TraitDescriptionDivine",
    "double-barrel": "XPRPG.TraitDescriptionDoubleBarrel",
    downtime: "XPRPG.TraitDescriptionDowntime",
    drug: "XPRPG.TraitDescriptionDrug",
    druid: "XPRPG.TraitDescriptionDruid",
    duskwalker: "XPRPG.TraitDescriptionDuskwalker",
    dwarf: "XPRPG.TraitDescriptionDwarf",
    earth: "XPRPG.TraitDescriptionEarth",
    eidolon: "XPRPG.TraitDescriptionEidolon",
    electricity: "XPRPG.TraitDescriptionElectricity",
    elf: "XPRPG.TraitDescriptionElf",
    elixir: "XPRPG.TraitDescriptionElixir",
    emotion: "XPRPG.TraitDescriptionEmotion",
    enchantment: "XPRPG.TraitDescriptionEnchantment",
    "entrench-melee": "XPRPG.TraitDescriptionEntrenchMelee",
    "entrench-ranged": "XPRPG.TraitDescriptionEntrenchRanged",
    environment: "XPRPG.TraitDescriptionEnvironment",
    esoterica: "XPRPG.TraitDescriptionEsoterica",
    evil: "XPRPG.TraitDescriptionEvil",
    evocation: "XPRPG.TraitDescriptionEvocation",
    expandable: "XPRPG.TraitDescriptionExpandable",
    exploration: "XPRPG.TraitDescriptionExploration",
    extradimensional: "XPRPG.TraitDescriptionExtradimensional",
    "fatal-aim-d10": "XPRPG.TraitDescriptionFatalAim",
    "fatal-aim-d12": "XPRPG.TraitDescriptionFatalAim",
    "fatal-d10": "XPRPG.TraitDescriptionFatal",
    "fatal-d12": "XPRPG.TraitDescriptionFatal",
    "fatal-d8": "XPRPG.TraitDescriptionFatal",
    fear: "XPRPG.TraitDescriptionFear",
    fetchling: "XPRPG.TraitDescriptionFetchling",
    fey: "XPRPG.TraitDescriptionFey",
    fighter: "XPRPG.TraitDescriptionFighter",
    finesse: "XPRPG.TraitDescriptionFinesse",
    finisher: "XPRPG.TraitDescriptionFinisher",
    fire: "XPRPG.TraitDescriptionFire",
    fleshwarp: "XPRPG.TraitDescriptionFleshwarp",
    flexible: "XPRPG.TraitDescriptionFlexible",
    flourish: "XPRPG.TraitDescriptionFlourish",
    focused: "XPRPG.TraitDescriptionFocused",
    foldaway: "XPRPG.TraitDescriptionFoldaway",
    force: "XPRPG.TraitDescriptionForce",
    forceful: "XPRPG.TraitDescriptionForceful",
    fortune: "XPRPG.TraitDescriptionFortune",
    "free-hand": "XPRPG.TraitDescriptionFreeHand",
    fulu: "XPRPG.TraitDescriptionFulu",
    fungus: "XPRPG.TraitDescriptionFungus",
    gadget: "XPRPG.TraitDescriptionGadget",
    ganzi: "XPRPG.TraitDescriptionGanzi",
    general: "XPRPG.TraitDescriptionGeneral",
    genie: "XPRPG.TraitDescriptionGenie",
    geniekin: "XPRPG.TraitDescriptionGeniekin",
    ghoran: "XPRPG.TraitDescriptionGhoran",
    ghul: "XPRPG.TraitDescriptionGhul",
    gnoll: "XPRPG.TraitDescriptionGnoll",
    gnome: "XPRPG.TraitDescriptionGnome",
    goblin: "XPRPG.TraitDescriptionGoblin",
    goloma: "XPRPG.TraitDescriptionGoloma",
    good: "XPRPG.TraitDescriptionGood",
    grapple: "XPRPG.TraitDescriptionGrapple",
    grimoire: "XPRPG.TraitDescriptionGrimoire",
    grippli: "XPRPG.TraitDescriptionGrippli",
    gunslinger: "XPRPG.TraitDescriptionGunslinger",
    halfling: "XPRPG.TraitDescriptionHalfling",
    "half-elf": "XPRPG.TraitDescriptionHalfElf",
    "half-orc": "XPRPG.TraitDescriptionHalfOrc",
    "jousting-d6": "XPRPG.TraitDescriptionJousting",
    hampering: "XPRPG.TraitDescriptionHampering",
    harnessed: "XPRPG.TraitDescriptionHarnessed",
    haunt: "XPRPG.TraitDescriptionHaunt",
    healing: "XPRPG.TraitDescriptionHealing",
    "hefty-14": "XPRPG.TraitDescriptionHefty",
    hex: "XPRPG.TraitDescriptionHex",
    hindering: "XPRPG.TraitDescriptionHindering",
    hobgoblin: "XPRPG.TraitDescriptionHobgoblin",
    human: "XPRPG.TraitDescriptionHuman",
    humanoid: "XPRPG.TraitDescriptionHumanoid",
    ifrit: "XPRPG.TraitDescriptionIfrit",
    illusion: "XPRPG.TraitDescriptionIllusion",
    incapacitation: "XPRPG.TraitDescriptionIncapacitation",
    incarnate: "XPRPG.TraitDescriptionIncarnate",
    incorporeal: "XPRPG.TraitDescriptionIncorporeal",
    infused: "XPRPG.TraitDescriptionInfused",
    ingested: "XPRPG.TraitDescriptionIngested",
    inhaled: "XPRPG.TraitDescriptionInhaled",
    injection: "XPRPG.TraitDescriptionInjection",
    injury: "XPRPG.TraitDescriptionInjury",
    inscribed: "XPRPG.TraitDescriptionInscribed",
    "integrated-1d6-b": "XPRPG.TraitDescriptionIntegrated",
    "integrated-1d6-p": "XPRPG.TraitDescriptionIntegrated",
    "integrated-1d6-s": "XPRPG.TraitDescriptionIntegrated",
    "integrated-1d6-s-versatile-p": "XPRPG.TraitDescriptionIntegrated",
    intelligent: "XPRPG.TraitDescriptionIntelligent",
    inventor: "XPRPG.TraitDescriptionInventor",
    invested: "XPRPG.TraitDescriptionInvested",
    investigator: "XPRPG.TraitDescriptionInvestigator",
    kashrishi: "XPRPG.TraitDescriptionKashrishi",
    kickback: "XPRPG.TraitDescriptionKickback",
    kitsune: "XPRPG.TraitDescriptionKitsune",
    kobold: "XPRPG.TraitDescriptionKobold",
    laminar: "XPRPG.TraitDescriptionLaminar",
    "launching-dart": "XPRPG.TraitDescriptionLaunching",
    lawful: "XPRPG.TraitDescriptionLawful",
    leshy: "XPRPG.TraitDescriptionLeshy",
    light: "XPRPG.TraitDescriptionLight",
    linguistic: "XPRPG.TraitDescriptionLinguistic",
    litany: "XPRPG.TraitDescriptionLitany",
    lizardfolk: "XPRPG.TraitDescriptionLizardfolk",
    lozenge: "XPRPG.TraitDescriptionLozenge",
    magical: "XPRPG.TraitDescriptionMagical",
    magus: "XPRPG.TraitDescriptionMagus",
    manipulate: "XPRPG.TraitDescriptionManipulate",
    mechanical: "XPRPG.TraitDescriptionMechanical",
    mental: "XPRPG.TraitDescriptionMental",
    metal: "XPRPG.TraitDescriptionMetal",
    metamagic: "XPRPG.TraitDescriptionMetamagic",
    mindless: "XPRPG.TraitDescriptionMindless",
    minion: "XPRPG.TraitDescriptionMinion",
    misfortune: "XPRPG.TraitDescriptionMisfortune",
    missive: "XPRPG.TraitDescriptionMissive",
    modification: "XPRPG.TraitDescriptionModification",
    modular: "XPRPG.TraitDescriptionModular",
    monk: "XPRPG.TraitDescriptionMonk",
    morph: "XPRPG.TraitDescriptionMorph",
    mounted: "XPRPG.TraitDescriptionMounted",
    move: "XPRPG.TraitDescriptionMove",
    multiclass: "XPRPG.TraitDescriptionMulticlass",
    mutagen: "XPRPG.TraitDescriptionMutagen",
    nagaji: "XPRPG.TraitDescriptionNagaji",
    necromancy: "XPRPG.TraitDescriptionNecromancy",
    negative: "XPRPG.TraitDescriptionNegative",
    noisy: "XPRPG.TraitDescriptionNoisy",
    nonlethal: "XPRPG.TraitDescriptionNonlethal",
    oath: "XPRPG.TraitDescriptionOath",
    occult: "XPRPG.TraitDescriptionOccult",
    oil: "XPRPG.TraitDescriptionOil",
    olfactory: "XPRPG.TraitDescriptionOlfactory",
    open: "XPRPG.TraitDescriptionOpen",
    oracle: "XPRPG.TraitDescriptionOracle",
    orc: "XPRPG.TraitDescriptionOrc",
    oread: "XPRPG.TraitDescriptionOread",
    parry: "XPRPG.TraitDescriptionParry",
    peachwood: "XPRPG.PreciousMaterialPeachwoodDescription",
    plant: "XPRPG.TraitDescriptionPlant",
    poison: "XPRPG.TraitDescriptionPoison",
    polymorph: "XPRPG.TraitDescriptionPolymorph",
    ponderous: "XPRPG.TraitDescriptionPonderous",
    poppet: "XPRPG.TraitDescriptionPoppet",
    portable: "XPRPG.TraitDescriptionPortable",
    positive: "XPRPG.TraitDescriptionPositive",
    possession: "XPRPG.TraitDescriptionPossession",
    potion: "XPRPG.TraitDescriptionPotion",
    precious: "XPRPG.TraitDescriptionPrecious",
    prediction: "XPRPG.TraitDescriptionPrediction",
    press: "XPRPG.TraitDescriptionPress",
    primal: "XPRPG.TraitDescriptionPrimal",
    propulsive: "XPRPG.TraitDescriptionPropulsive",
    psyche: "XPRPG.TraitDescriptionPsyche",
    psychic: "XPRPG.TraitDescriptionPsychic",
    rage: "XPRPG.TraitDescriptionRage",
    ranger: "XPRPG.TraitDescriptionRanger",
    ...rangeDescriptions,
    "ranged-trip": "XPRPG.TraitDescriptionRangedTrip",
    rare: "XPRPG.TraitDescriptionRare",
    ratfolk: "XPRPG.TraitDescriptionRatfolk",
    razing: "XPRPG.TraitDescriptionRazing",
    reach: "XPRPG.TraitDescriptionReach",
    "reach-0": "XPRPG.TraitDescriptionReach",
    "reach-10": "XPRPG.TraitDescriptionReach",
    "reach-100": "XPRPG.TraitDescriptionReach",
    "reach-1000": "XPRPG.TraitDescriptionReach",
    "reach-15": "XPRPG.TraitDescriptionReach",
    "reach-20": "XPRPG.TraitDescriptionReach",
    "reach-25": "XPRPG.TraitDescriptionReach",
    "reach-30": "XPRPG.TraitDescriptionReach",
    "reach-40": "XPRPG.TraitDescriptionReach",
    "reach-50": "XPRPG.TraitDescriptionReach",
    "reach-60": "XPRPG.TraitDescriptionReach",
    recovery: "XPRPG.TraitDescriptionRecovery",
    reflection: "XPRPG.TraitDescriptionReflection",
    reload: "XPRPG.TraitDescriptionReload",
    "reload-0": "XPRPG.TraitDescriptionReload",
    "reload-1": "XPRPG.TraitDescriptionReload",
    "reload-1-min": "XPRPG.TraitDescriptionReload",
    "reload-2": "XPRPG.TraitDescriptionReload",
    repeating: "XPRPG.TraitDescriptionRepeating",
    resonant: "XPRPG.TraitDescriptionResonant",
    revelation: "XPRPG.TraitDescriptionRevelation",
    rogue: "XPRPG.TraitDescriptionRogue",
    saggorak: "XPRPG.TraitDescriptionSaggorak",
    "scatter-10": "XPRPG.TraitDescriptionScatter",
    "scatter-15": "XPRPG.TraitDescriptionScatter",
    "scatter-5": "XPRPG.TraitDescriptionScatter",
    scroll: "XPRPG.TraitDescriptionScroll",
    scrying: "XPRPG.TraitDescriptionScrying",
    secret: "XPRPG.TraitDescriptionSecret",
    shadow: "XPRPG.TraitDescriptionShadow",
    "shield-throw-20": "XPRPG.TraitDescriptionShieldThrow",
    "shield-throw-30": "XPRPG.TraitDescriptionShieldThrow",
    shisk: "XPRPG.TraitDescriptionShisk",
    shoony: "XPRPG.TraitDescriptionShoony",
    shove: "XPRPG.TraitDescriptionShove",
    skeleton: "XPRPG.TraitDescriptionSkeleton",
    skill: "XPRPG.TraitDescriptionSkill",
    sleep: "XPRPG.TraitDescriptionSleep",
    snare: "XPRPG.TraitDescriptionSnare",
    social: "XPRPG.TraitDescriptionSocial",
    sonic: "XPRPG.TraitDescriptionSonic",
    sorcerer: "XPRPG.TraitDescriptionSorcerer",
    spellgun: "XPRPG.TraitDescriptionSpellgun",
    spellheart: "XPRPG.TraitDescriptionSpellheart",
    spellshot: "XPRPG.TraitNoDescription",
    splash: "XPRPG.TraitDescriptionSplash",
    "splash-10": "XPRPG.TraitDescriptionSplash10",
    sprite: "XPRPG.TraitDescriptionSprite",
    staff: "XPRPG.TraitDescriptionStaff",
    stance: "XPRPG.TraitDescriptionStance",
    steam: "XPRPG.TraitDescriptionSteam",
    strix: "XPRPG.TraitDescriptionStrix",
    structure: "XPRPG.TraitDescriptionStructure",
    suli: "XPRPG.TraitDescriptionSuli",
    summon: "XPRPG.TraitDescriptionSummon",
    summoned: "XPRPG.TraitDescriptionSummoned",
    summoner: "XPRPG.TraitDescriptionSummoner",
    swashbuckler: "XPRPG.TraitDescriptionSwashbuckler",
    sweep: "XPRPG.TraitDescriptionSweep",
    sylph: "XPRPG.TraitDescriptionSylph",
    talisman: "XPRPG.TraitDescriptionTalisman",
    tattoo: "XPRPG.TraitDescriptionTattoo",
    tech: "XPRPG.TraitDescriptionTech",
    telepathy: "XPRPG.TraitDescriptionTelepathy",
    teleportation: "XPRPG.TraitDescriptionTeleportation",
    tengu: "XPRPG.TraitDescriptionTengu",
    tethered: "XPRPG.TraitDescriptionTethered",
    thaumaturge: "XPRPG.TraitDescriptionThaumaturge",
    thrown: "XPRPG.TraitDescriptionThrown",
    "thrown-10": "XPRPG.TraitDescriptionThrown",
    "thrown-100": "XPRPG.TraitDescriptionThrown",
    "thrown-15": "XPRPG.TraitDescriptionThrown",
    "thrown-20": "XPRPG.TraitDescriptionThrown",
    "thrown-200": "XPRPG.TraitDescriptionThrown",
    "thrown-25": "XPRPG.TraitDescriptionThrown",
    "thrown-30": "XPRPG.TraitDescriptionThrown",
    "thrown-40": "XPRPG.TraitDescriptionThrown",
    "thrown-50": "XPRPG.TraitDescriptionThrown",
    "thrown-60": "XPRPG.TraitDescriptionThrown",
    "thrown-80": "XPRPG.TraitDescriptionThrown",
    tiefling: "XPRPG.TraitDescriptionTiefling",
    time: "XPRPG.TraitDescriptionTime",
    training: "XPRPG.TraitDescriptionTraining",
    transmutation: "XPRPG.TraitDescriptionTransmutation",
    trap: "XPRPG.TraitDescriptionTrap",
    trip: "XPRPG.TraitDescriptionTrip",
    "true-name": "XPRPG.TraitDescriptionTrueName",
    twin: "XPRPG.TraitDescriptionTwin",
    "two-hand-d10": "XPRPG.TraitDescriptionTwoHand",
    "two-hand-d12": "XPRPG.TraitDescriptionTwoHand",
    "two-hand-d6": "XPRPG.TraitDescriptionTwoHand",
    "two-hand-d8": "XPRPG.TraitDescriptionTwoHand",
    unarmed: "XPRPG.TraitDescriptionUnarmed",
    uncommon: "XPRPG.TraitDescriptionUncommon",
    undine: "XPRPG.TraitDescriptionUndine",
    unique: "XPRPG.TraitDescriptionUnique",
    unstable: "XPRPG.TraitDescriptionUnstable",
    vanara: "XPRPG.TraitDescriptionVanara",
    vishkanya: "XPRPG.TraitDescriptionVishkanya",
    vehicular: "XPRPG.TraitDescriptionVehicular",
    "versatile-acid": "XPRPG.TraitDescriptionVersatile",
    "versatile-b": "XPRPG.TraitDescriptionVersatile",
    "versatile-chaotic": "XPRPG.TraitDescriptionVersatile",
    "versatile-cold": "XPRPG.TraitDescriptionVersatile",
    "versatile-electricity": "XPRPG.TraitDescriptionVersatile",
    "versatile-evil": "XPRPG.TraitDescriptionVersatile",
    "versatile-fire": "XPRPG.TraitDescriptionVersatile",
    "versatile-force": "XPRPG.TraitDescriptionVersatile",
    "versatile-good": "XPRPG.TraitDescriptionVersatile",
    "versatile-lawful": "XPRPG.TraitDescriptionVersatile",
    "versatile-negative": "XPRPG.TraitDescriptionVersatile",
    "versatile-p": "XPRPG.TraitDescriptionVersatile",
    "versatile-positive": "XPRPG.TraitDescriptionVersatile",
    "versatile-s": "XPRPG.TraitDescriptionVersatile",
    "versatile-sonic": "XPRPG.TraitDescriptionVersatile",
    virulent: "XPRPG.TraitDescriptionVirulent",
    visual: "XPRPG.TraitDescriptionVisual",
    "volley-20": "XPRPG.TraitDescriptionVolley",
    "volley-30": "XPRPG.TraitDescriptionVolley",
    "volley-50": "XPRPG.TraitDescriptionVolley",
    wand: "XPRPG.TraitDescriptionWand",
    water: "XPRPG.TraitDescriptionWater",
    witch: "XPRPG.TraitDescriptionWitch",
    wizard: "XPRPG.TraitDescriptionWizard",
    ...preciousMaterialDescriptions,
};

const preciousMaterialGrades: Record<PreciousMaterialGrade, string> = {
    low: "XPRPG.PreciousMaterialLowGrade",
    standard: "XPRPG.PreciousMaterialStandardGrade",
    high: "XPRPG.PreciousMaterialHighGrade",
};

const meleeWeaponGroups: Record<MeleeWeaponGroup, string> = {
    axe: "XPRPG.WeaponGroupAxe",
    brawling: "XPRPG.WeaponGroupBrawling",
    club: "XPRPG.WeaponGroupClub",
    dart: "XPRPG.WeaponGroupDart",
    flail: "XPRPG.WeaponGroupFlail",
    hammer: "XPRPG.WeaponGroupHammer",
    knife: "XPRPG.WeaponGroupKnife",
    pick: "XPRPG.WeaponGroupPick",
    polearm: "XPRPG.WeaponGroupPolearm",
    shield: "XPRPG.WeaponGroupShield",
    spear: "XPRPG.WeaponGroupSpear",
    sword: "XPRPG.WeaponGroupSword",
};

const weaponGroups: Record<WeaponGroup, string> = {
    ...meleeWeaponGroups,
    bomb: "XPRPG.WeaponGroupBomb",
    bow: "XPRPG.WeaponGroupBow",
    firearm: "XPRPG.WeaponGroupFirearm",
    sling: "XPRPG.WeaponGroupSling",
};

// Creature and Equipment Sizes
const sizeTypes: Record<Size, string> = {
    tiny: "XPRPG.ActorSizeTiny",
    sm: "XPRPG.ActorSizeSmall",
    med: "XPRPG.ActorSizeMedium",
    lg: "XPRPG.ActorSizeLarge",
    huge: "XPRPG.ActorSizeHuge",
    grg: "XPRPG.ActorSizeGargantuan",
};

const featTypes: Record<FeatType, string> = {
    ancestry: "XPRPG.FeatTypeAncestry",
    ancestryfeature: "XPRPG.FeatTypeAncestryfeature",
    class: "XPRPG.FeatTypeClass",
    classfeature: "XPRPG.FeatTypeClassfeature",
    skill: "XPRPG.FeatTypeSkill",
    general: "XPRPG.FeatTypeGeneral",
    archetype: "XPRPG.FeatTypeArchetype",
    bonus: "XPRPG.FeatTypeBonus",
    xpsboon: "XPRPG.FeatPFSBoonHeader",
    deityboon: "XPRPG.FeatDeityBoonHeader",
    curse: "XPRPG.FeatCurseHeader",
};

const alignments: Record<Alignment, string> = {
    LG: "XPRPG.AlignmentLG",
    NG: "XPRPG.AlignmentNG",
    CG: "XPRPG.AlignmentCG",
    LN: "XPRPG.AlignmentLN",
    N: "XPRPG.AlignmentN",
    CN: "XPRPG.AlignmentCN",
    LE: "XPRPG.AlignmentLE",
    NE: "XPRPG.AlignmentNE",
    CE: "XPRPG.AlignmentCE",
};

const deityDomains = Object.keys(enJSON.XPRPG.Item.Deity.Domain).reduce((domains, key) => {
    const slug = sluggify(key);
    const casedKey = sluggify(key, { camel: "bactrian" });
    return {
        ...domains,
        [slug]: {
            label: `XPRPG.Item.Deity.Domain.${casedKey}.Label`,
            description: `XPRPG.Item.Deity.Domain.${casedKey}.Description`,
        },
    };
}, {} as Record<DeityDomain, { label: string; description: string }>);

const weaponReload: Record<WeaponReloadTime, string> = {
    "-": "—", // Reload value for thrown weapons
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    10: "XPRPG.Item.Weapon.ReloadOneMinute",
};

export const XPRPGCONFIG = {
    chatDamageButtonShieldToggle: false,

    statusEffects: {
        lastIconTheme: "default" as StatusEffectIconTheme,
        iconDir: "systems/xprpg/icons/conditions/",
        conditions: tokenHUDConditions,
    },

    levels: {
        1: "XPRPG.Level1",
        2: "XPRPG.Level2",
        3: "XPRPG.Level3",
        4: "XPRPG.Level4",
        5: "XPRPG.Level5",
        6: "XPRPG.Level6",
        7: "XPRPG.Level7",
        8: "XPRPG.Level8",
        9: "XPRPG.Level9",
        10: "XPRPG.Level10",
        11: "XPRPG.Level11",
        12: "XPRPG.Level12",
        13: "XPRPG.Level13",
        14: "XPRPG.Level14",
        15: "XPRPG.Level15",
        16: "XPRPG.Level16",
        17: "XPRPG.Level17",
        18: "XPRPG.Level18",
        19: "XPRPG.Level19",
        20: "XPRPG.Level20",
    },

    abilities: {
        str: "XPRPG.AbilityStr",
        dex: "XPRPG.AbilityDex",
        con: "XPRPG.AbilityCon",
        int: "XPRPG.AbilityInt",
        wis: "XPRPG.AbilityWis",
        cha: "XPRPG.AbilityCha",
    },

    attributes: {
        perception: "XPRPG.PerceptionLabel",
        stealth: "XPRPG.StealthLabel",
        initiative: "XPRPG.PerceptionLabel",
    },

    dcAdjustments: {
        "incredibly easy": "XPRPG.DCAdjustmentIncrediblyEasy",
        "very easy": "XPRPG.DCAdjustmentVeryEasy",
        easy: "XPRPG.DCAdjustmentEasy",
        normal: "XPRPG.DCAdjustmentNormal",
        hard: "XPRPG.DCAdjustmentHard",
        "very hard": "XPRPG.DCAdjustmentVeryHard",
        "incredibly hard": "XPRPG.DCAdjustmentIncrediblyHard",
    },

    skills: {
        acr: "XPRPG.SkillAcr",
        arc: "XPRPG.SkillArc",
        ath: "XPRPG.SkillAth",
        cra: "XPRPG.SkillCra",
        dec: "XPRPG.SkillDec",
        dip: "XPRPG.SkillDip",
        itm: "XPRPG.SkillItm",
        med: "XPRPG.SkillMed",
        nat: "XPRPG.SkillNat",
        occ: "XPRPG.SkillOcc",
        prf: "XPRPG.SkillPrf",
        rel: "XPRPG.SkillRel",
        soc: "XPRPG.SkillSoc",
        ste: "XPRPG.SkillSte",
        sur: "XPRPG.SkillSur",
        thi: "XPRPG.SkillThi",
    },

    martialSkills: {
        unarmored: "XPRPG.MartialUnarmored",
        light: "XPRPG.MartialLight",
        medium: "XPRPG.MartialMedium",
        heavy: "XPRPG.MartialHeavy",
        simple: "XPRPG.MartialSimple",
        martial: "XPRPG.MartialMartial",
        advanced: "XPRPG.MartialAdvanced",
        unarmed: "XPRPG.MartialUnarmed",
    },

    saves: {
        fortitude: "XPRPG.SavesFortitude",
        reflex: "XPRPG.SavesReflex",
        will: "XPRPG.SavesWill",
    },

    savingThrowDefaultAbilities: {
        fortitude: "con",
        reflex: "dex",
        will: "wis",
    } as const,

    currencies: {
        pp: "XPRPG.CurrencyPP",
        gp: "XPRPG.CurrencyGP",
        sp: "XPRPG.CurrencySP",
        cp: "XPRPG.CurrencyCP",
    },

    preciousMaterialGrades,
    preciousMaterials,

    armorPotencyRunes: {
        "1": "XPRPG.ArmorPotencyRune1",
        "2": "XPRPG.ArmorPotencyRune2",
        "3": "XPRPG.ArmorPotencyRune3",
        "4": "XPRPG.ArmorPotencyRune4",
    },

    armorResiliencyRunes: {
        resilient: "XPRPG.ArmorResilientRune",
        greaterResilient: "XPRPG.ArmorGreaterResilientRune",
        majorResilient: "XPRPG.ArmorMajorResilientRune",
    },
    armorPropertyRunes: {
        ready: "XPRPG.ArmorPropertyRuneReady",
        slick: "XPRPG.ArmorPropertyRuneSlick",
        shadow: "XPRPG.ArmorPropertyRuneShadow",
        glamered: "XPRPG.ArmorPropertyRuneGlamered",
        acidResistant: "XPRPG.ArmorPropertyRuneAcidResistant",
        coldResistant: "XPRPG.ArmorPropertyRuneColdResistant",
        electricityResistant: "XPRPG.ArmorPropertyRuneElectricityResistant",
        fireResistant: "XPRPG.ArmorPropertyRuneFireResistant",
        greaterSlick: "XPRPG.ArmorPropertyRuneGreaterSlick",
        invisibility: "XPRPG.ArmorPropertyRuneInvisibility",
        sinisterKnight: "XPRPG.ArmorPropertyRuneSinisterKnight",
        greaterDread: "XPRPG.ArmorPropertyRuneGreaterDread",
        greaterReady: "XPRPG.ArmorPropertyRuneGreaterReady",
        greaterShadow: "XPRPG.ArmorPropertyRuneGreaterShadow",
        greaterInvisibility: "XPRPG.ArmorPropertyRuneGreaterInvisibility",
        greaterAcidResistant: "XPRPG.ArmorPropertyRuneGreaterAcidResistant",
        greaterColdResistant: "XPRPG.ArmorPropertyRuneGreaterColdResistant",
        greaterElectricityResistant: "XPRPG.ArmorPropertyRuneGreaterElectricityResistant",
        greaterFireResistant: "XPRPG.ArmorPropertyRuneGreaterFireResistant",
        fortification: "XPRPG.ArmorPropertyRuneFortification",
        winged: "XPRPG.ArmorPropertyRuneWinged",
        rockBraced: "XPRPG.ArmorPropertyRuneRockBraced",
        soaring: "XPRPG.ArmorPropertyRuneSoaring",
        antimagic: "XPRPG.ArmorPropertyRuneAntimagic",
        majorSlick: "XPRPG.ArmorPropertyRuneMajorSlick",
        ethereal: "XPRPG.ArmorPropertyRuneEthereal",
        majorShadow: "XPRPG.ArmorPropertyRuneMajorShadow",
        moderateDread: "XPRPG.ArmorPropertyRuneModerateDread",
        greaterFortification: "XPRPG.ArmorPropertyRuneGreaterFortification",
        greaterWinged: "XPRPG.ArmorPropertyRuneGreaterWinged",
        deathless: "XPRPG.ArmorPropertyRuneDeathless",
        dread: "XPRPG.ArmorPropertyRuneDread",
        bitter: "XPRPG.ArmorPropertyRuneBitter",
        stanching: "XPRPG.ArmorPropertyRuneStanching",
        greaterStanching: "XPRPG.ArmorPropertyRuneGreaterStanching",
        majorStanching: "XPRPG.ArmorPropertyRuneMajorStanching",
        trueStanching: "XPRPG.ArmorPropertyRuneTrueStanching",
        implacable: "XPRPG.ArmorPropertyRuneImplacable",
    },
    accessoryPropertyRunes: {
        called: "XPRPG.AccessoryPropertyRuneCalled",
        dragonsBreath: "XPRPG.AccessoryPropertyRuneDragonsBreath",
        paired: "XPRPG.AccessoryPropertyRunePaired",
        greaterPaired: "XPRPG.AccessoryPropertyRuneGreaterPaired",
        majorPaired: "XPRPG.AccessoryPropertyRuneMajorPaired",
        presentable: "XPRPG.AccessoryPropertyRunePresentable",
        snagging: "XPRPG.AccessoryPropertyRuneSnagging",
        softLanding: "XPRPG.AccessoryPropertyRuneSoftLanding",
        spellBastion: "XPRPG.AccessoryPropertyRuneSpellBastion",
        windCatcher: "XPRPG.AccessoryPropertyRuneWindCatcher",
        greaterWindCatcher: "XPRPG.AccessoryPropertyRuneGreaterWindCatcher",
    },
    weaponPotencyRunes: {
        1: "XPRPG.WeaponPotencyRune1",
        2: "XPRPG.WeaponPotencyRune2",
        3: "XPRPG.WeaponPotencyRune3",
        4: "XPRPG.WeaponPotencyRune4",
    },
    weaponStrikingRunes: {
        striking: "XPRPG.ArmorStrikingRune",
        greaterStriking: "XPRPG.ArmorGreaterStrikingRune",
        majorStriking: "XPRPG.ArmorMajorStrikingRune",
    },
    weaponPropertyRunes,
    damageTraits,
    damageTypes,
    damageRollFlavors,
    damageCategories,
    materialDamageEffects,
    resistanceTypes,

    stackGroups: {
        arrows: "XPRPG.StackGroupArrows",
        blowgunDarts: "XPRPG.StackGroupBlowgunDarts",
        bolts: "XPRPG.StackGroupBolts",
        coins: "XPRPG.StackGroupCoins",
        gems: "XPRPG.StackGroupGems",
        rounds5: "XPRPG.StackGroupRounds5",
        rounds10: "XPRPG.StackGroupRounds10",
        rations: "XPRPG.StackGroupRations",
        sacks: "XPRPG.StackGroupSacks",
        slingBullets: "XPRPG.StackGroupSlingBullets",
        sprayPellets: "XPRPG.StackGroupSprayPellets",
        woodenTaws: "XPRPG.StackGroupWoodenTaws",
    },

    weaknessTypes,

    weaponDamage: {
        bludgeoning: "XPRPG.TraitBludgeoning",
        piercing: "XPRPG.TraitPiercing",
        slashing: "XPRPG.TraitSlashing",
        modular: "XPRPG.TraitModular",
    },

    healingTypes: {
        healing: "XPRPG.TraitHealing",
        temphp: "XPRPG.HealingTypeTemporaryHealing",
    },

    weaponCategories,
    weaponGroups,
    meleeWeaponGroups,

    baseWeaponTypes,
    equivalentWeapons,

    weaponDescriptions: {
        club: "XPRPG.WeaponDescriptionClub",
        knife: "XPRPG.WeaponDescriptionKnife",
        brawling: "XPRPG.WeaponDescriptionBrawling",
        spear: "XPRPG.WeaponDescriptionSpear",
        sword: "XPRPG.WeaponDescriptionSword",
        axe: "XPRPG.WeaponDescriptionAxe",
        flail: "XPRPG.WeaponDescriptionFlail",
        polearm: "XPRPG.WeaponDescriptionPolearm",
        pick: "XPRPG.WeaponDescriptionPick",
        hammer: "XPRPG.WeaponDescriptionHammer",
        shield: "XPRPG.WeaponDescriptionShield",
        dart: "XPRPG.WeaponDescriptionDart",
        bow: "XPRPG.WeaponDescriptionBow",
        sling: "XPRPG.WeaponDescriptionSling",
        bomb: "XPRPG.WeaponDescriptionBomb",
    },

    usageTraits: {
        "affixed-to-a-creature": "XPRPG.TraitAffixedToCreature",
        "affixed-to-a-magical-staff": "XPRPG.TraitAffixedToMagicalStaff",
        "affixed-to-a-ranged-weapon": "XPRPG.TraitAffixedToARangedWeapon",
        "affixed-to-a-shield": "XPRPG.TraitAffixedToAShield",
        "affixed-to-a-thrown-weapon": "XPRPG.TraitAffixedToThrownWeapon",
        "affixed-to-a-two-handed-firearm-or-crossbow": "XPRPG.TraitAffixedToATwoHandedFirearmOrCrossbow",
        "affixed-to-an-innovation": "XPRPG.TraitAffixedToInnovation",
        "affixed-to-an-object-or-structure": "XPRPG.TraitAffixedToObjectOrStructure",
        "affixed-to-armor": "XPRPG.TraitAffixedToArmor",
        "affixed-to-medium-heavy-armor": "XPRPG.TraitAffixedToMediumHeavyArmor",
        "affixed-to-armor-or-a-weapon": "XPRPG.TraitAffixedToArmorOrAWeapon",
        "affixed-to-armor-or-travelers-clothing": "XPRPG.TraitAffixedToArmorOrTravelersClothing",
        "affixed-to-crossbow-or-firearm": "XPRPG.TraitAffixedToCrossbowOrFirearm",
        "affixed-to-firearm": "XPRPG.TraitAffixedToFirearm",
        "affixed-to-firearm-with-a-reload-of-1": "XPRPG.TraitAffixedToFirearmWithAReloadOf1",
        "affixed-to-firearm-with-the-kickback-trait": "XPRPG.TraitAffixedToFirearmWithTheKickbackTrait",
        "affixed-to-ground-in-10-foot-radius": "XPRPG.TraitAffixedToGroundIn10FtRadius",
        "affixed-to-ground-in-20-foot-radius": "XPRPG.TraitAffixedToGroundIn20FtRadius",
        "affixed-to-harness": "XPRPG.TraitAffixedToHarness",
        "affixed-to-headgear": "XPRPG.TraitAffixedToHeadgear",
        "affixed-to-instrument": "XPRPG.TraitAffixedToInstrument",
        "affixed-to-load-bearing-wall-or-pillar": "XPRPG.TraitAffixedToLoadBearingWallOrPillar",
        "affixed-to-object-structure-or-creature": "XPRPG.TraitAffixedToStructureObjectOrCreature",
        "affixed-to-the-ground": "XPRPG.TraitAffixedToGround",
        "affixed-to-unarmored-defense-item": "XPRPG.TraitAffixedToUnarmoredItem",
        "affixed-to-weapon": "XPRPG.TraitAffixedToWeapon",
        "applied-to-a-basket-bag-or-other-container": "XPRPG.TraitAppliedToBasketBagOrContainer",
        "applied-to-a-wind-powered-vehicle": "XPRPG.TraitAppliedToAWindPoweredVehicle",
        "applied-to-a-non-injection-melee-weapon-piercing-damage":
            "XPRPG.TraitAppliedToANoninjectionMeleePiercingWeapon",
        "applied-to-any-item-of-light-or-negligible-bulk": "XPRPG.TraitAppliedToAnyItemOfLightOrNegligibleBulk",
        "applied-to-any-visible-article-of-clothing": "XPRPG.TraitAppliedToAnyVisibleArticleOfClothing",
        "applied-to-armor": "XPRPG.TraitAppliedToArmor",
        "applied-to-armor-or-unarmored-defense-clothing": "XPRPG.TraitAppliedToArmorOrUnarmored",
        "applied-to-belt-cape-cloak-or-scarf": "XPRPG.TraitAppliedToBeltCapeCloakOrScarf",
        "applied-to-boots-cape-cloak-or-umbrella": "XPRPG.TraitAppliedToBootsCapeCloakOrUmbrella",
        "applied-to-buckler-shield": "XPRPG.TraitAppliedToBucklerShield",
        "applied-to-dueling-cape-or-shield": "XPRPG.TraitAppliedToDuelingCapeOrShield",
        "applied-to-footwear": "XPRPG.TraitAppliedToFootwear",
        "applied-to-medium-heavy-armor": "XPRPG.TraitAppliedToMediumHeavyArmor",
        "applied-to-shield": "XPRPG.TraitAppliedToShield",
        "attached-to-a-thrown-weapon": "XPRPG.TraitAttachedToAThrownWeapon",
        "attached-to-crossbow-or-firearm": "XPRPG.TraitAttachedToCrossbowOrFirearm",
        "attached-to-crossbow-or-firearm-firing-mechanism": "XPRPG.TraitAttachedToCrossbowOrFirearmFiringMechanism",
        "attached-to-crossbow-or-firearm-scope": "XPRPG.TraitAttachedToCrossbowOrFirearmScope",
        "attached-to-firearm": "XPRPG.TraitAttachedToFirearm",
        "attached-to-firearm-scope": "XPRPG.TraitAttachedToFirearmScope",
        bonded: "XPRPG.TraitBonded",
        "each-rune-applied-to-a-separate-item-that-has-pockets":
            "XPRPG.TraitEachRuneAppliedToASeparateItemThatHasPockets",
        "etched-onto-a-weapon": "XPRPG.TraitEtchedOntoAWeapon",
        "etched-onto-armor": "XPRPG.TraitEtchedOntoArmor",
        "etched-onto-heavy-armor": "XPRPG.TraitEtchedOntoHeavyArmor",
        "etched-onto-light-armor": "XPRPG.TraitEtchedOntoLightArmor",
        "etched-onto-metal-armor": "XPRPG.TraitEtchedOntoMetalArmor",
        "etched-onto-clan-dagger": "XPRPG.TraitEtchedOntoAClanDagger",
        "etched-onto-lm-nonmetal-armor": "XPRPG.TraitEtchedOntoLightMedNMArmor",
        "etched-onto-med-heavy-armor": "XPRPG.TraitEtchedOntoMedHeavyArmor",
        "etched-onto-melee-weapon": "XPRPG.TraitEtchedOntoAMeleeWeapon",
        "etched-onto-slashing-melee-weapon": "XPRPG.TraitEtchedOntoASlashingMeleeWeapon",
        "etched-onto-piercing-or-slashing-melee-weapon": "XPRPG.TraitEtchedOntoAPiercingOrSlashingMeleeWeapon",
        "etched-onto-weapon-wo-anarchic-rune": "XPRPG.TraitEtchedOntoAWeaponWOAxiomaticRune",
        "etched-onto-weapon-wo-axiomatic-rune": "XPRPG.TraitEtchedOntoAWeaponWOAnarchicRune",
        "etched-onto-weapon-wo-unholy-rune": "XPRPG.TraitEtchedOntoAWeaponWOHolyRune",
        "etched-onto-weapon-wo-holy-rune": "XPRPG.TraitEtchedOntoAWeaponWOUnholyRune",
        "etched-onto-melee-weapon-monk": "XPRPG.TraitEtchedOntoAMeleeWeaponMonk",
        "etched-onto-thrown-weapon": "XPRPG.TraitEtchedOntoAThrownWeapon",
        "held-in-one-hand": "XPRPG.TraitHeldOneHand",
        "held-in-one-hand-or-free-standing": "XPRPG.TraitHeldOneHandFreeStanding",
        "held-in-two-hands": "XPRPG.TraitHeldTwoHands",
        other: "Other",
        "sewn-into-clothing": "XPRPG.TraitSewnIntoClothing",
        "tattooed-on-the-body": "XPRPG.TraitTattooedOnTheBody",
        touched: "XPRPG.TraitTouched",
        worn: "XPRPG.TraitWorn",
        wornamulet: "XPRPG.TraitWornAmulet",
        wornanklets: "XPRPG.TraitWornAnklets",
        wornarmbands: "XPRPG.TraitWornArmbands",
        wornbackpack: "XPRPG.TraitWornBackpack",
        wornbarding: "XPRPG.TraitWornBarding",
        wornbelt: "XPRPG.TraitWornBelt",
        wornbeltpouch: "XPRPG.TraitWornBeltPouch",
        wornboots: "XPRPG.TraitWornBoots",
        wornbracelet: "XPRPG.TraitWornBracelet",
        wornbracers: "XPRPG.TraitWornBracers",
        worncap: "XPRPG.TraitWornCap",
        worncape: "XPRPG.TraitWornCape",
        worncirclet: "XPRPG.TraitWornCirclet",
        worncloak: "XPRPG.TraitWornCloak",
        wornclothing: "XPRPG.TraitWornClothing",
        worncollar: "XPRPG.TraitWornCollar",
        worncrown: "XPRPG.TraitWornCrown",
        wornepaulet: "XPRPG.TraitWornEpaulet",
        worneyeglasses: "XPRPG.TraitWornEyeglasses",
        worneyepiece: "XPRPG.TraitWornEyepiece",
        wornfootwear: "XPRPG.TraitWornFootwear",
        worngarment: "XPRPG.TraitWornGarment",
        worngloves: "XPRPG.TraitWornGloves",
        wornheadwear: "XPRPG.TraitWornHeadwear",
        wornhorseshoes: "XPRPG.TraitWornHorseshoes",
        wornmask: "XPRPG.TraitWornMask",
        wornnecklace: "XPRPG.TraitWornNecklace",
        wornonbelt: "XPRPG.TraitWornOnBelt",
        wornoronehand: "XPRPG.TraitWornOrOneHand",
        wornring: "XPRPG.TraitWornRing",
        wornsaddle: "XPRPG.TraitWornSaddle",
        wornsandles: "XPRPG.TraitWornSandles",
        wornshoes: "XPRPG.TraitWornShoes",
        wornwrist: "XPRPG.TraitWornOnWrists",
        "worn-and-attached-to-two-weapons": "XPRPG.TraitWornAndAttachedToTwoWeapons",
        "worn-under-armor": "XPRPG.TraitWornUnderArmor",
    },

    rarityTraits: {
        common: "XPRPG.TraitCommon",
        uncommon: "XPRPG.TraitUncommon",
        rare: "XPRPG.TraitRare",
        unique: "XPRPG.TraitUnique",
    },

    magicTraditions,
    spellOtherTraits,

    magicSchools,
    classTraits,
    ancestryTraits,
    ancestryItemTraits,
    deityDomains,

    weaponTraits,
    otherWeaponTags,

    armorTraits,
    otherArmorTags,

    equipmentTraits,

    consumableTraits,
    otherConsumableTags,

    actionTraits,
    spellTraits,
    featTraits,
    creatureTraits,
    monsterTraits: creatureTraits,
    npcAttackTraits,
    hazardTraits,
    vehicleTraits,

    traitsDescriptions,

    weaponHands: {
        1: "XPRPG.WeaponHands1",
        "1+": "XPRPG.WeaponHands1Plus",
        2: "XPRPG.WeaponHands2",
    },

    itemBonuses: {
        "-2": "XPRPG.ItemBonusMinus2",
        0: "XPRPG.ItemBonus0",
        1: "XPRPG.ItemBonus1",
        2: "XPRPG.ItemBonus2",
        3: "XPRPG.ItemBonus3",
    },

    damageDice: {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
    },

    damageDie: {
        d4: "XPRPG.DamageDieD4",
        d6: "XPRPG.DamageDieD6",
        d8: "XPRPG.DamageDieD8",
        d10: "XPRPG.DamageDieD10",
        d12: "XPRPG.DamageDieD12",
    },

    weaponMAP: {
        1: "-1/-2",
        2: "-2/-4",
        3: "-3/-6",
        4: "-4/-8",
        5: "-5/-10",
    },

    weaponReload,

    armorTypes: {
        unarmored: "XPRPG.ArmorTypeUnarmored",
        light: "XPRPG.ArmorTypeLight",
        medium: "XPRPG.ArmorTypeMedium",
        heavy: "XPRPG.ArmorTypeHeavy",
        shield: "XPRPG.ArmorTypeShield",
    },

    armorGroups: {
        composite: "XPRPG.ArmorGroupComposite",
        chain: "XPRPG.ArmorGroupChain",
        cloth: "XPRPG.ArmorGroupCloth",
        leather: "XPRPG.ArmorGroupLeather",
        plate: "XPRPG.ArmorGroupPlate",
        skeletal: "XPRPG.ArmorGroupSkeletal",
        wood: "XPRPG.ArmorGroupWood",
    },

    consumableTypes: {
        ammo: "XPRPG.ConsumableTypeAmmo",
        catalyst: "XPRPG.TraitCatalyst",
        drug: "XPRPG.ConsumableTypeDrug",
        elixir: "XPRPG.ConsumableTypeElixir",
        fulu: "XPRPG.TraitFulu",
        gadget: "XPRPG.TraitGadget",
        oil: "XPRPG.ConsumableTypeOil",
        other: "XPRPG.ConsumableTypeOther",
        mutagen: "XPRPG.ConsumableTypeMutagen",
        poison: "XPRPG.ConsumableTypePoison",
        potion: "XPRPG.ConsumableTypePotion",
        scroll: "XPRPG.ConsumableTypeScroll",
        snare: "XPRPG.ConsumableTypeSnare",
        talisman: "XPRPG.ConsumableTypeTalisman",
        tool: "XPRPG.ConsumableTypeTool",
        wand: "XPRPG.ConsumableTypeWand",
    },

    preparationType: {
        prepared: "XPRPG.PreparationTypePrepared",
        spontaneous: "XPRPG.PreparationTypeSpontaneous",
        innate: "XPRPG.PreparationTypeInnate",
        focus: "XPRPG.SpellCategoryFocus",
        ritual: "XPRPG.SpellCategoryRitual",
        items: "XPRPG.PreparationTypeItems",
    },

    areaTypes: {
        burst: "XPRPG.AreaTypeBurst",
        cone: "XPRPG.AreaTypeCone",
        cube: "XPRPG.AreaTypeCube",
        emanation: "XPRPG.AreaTypeEmanation",
        line: "XPRPG.AreaTypeLine",
        square: "XPRPG.AreaTypeSquare",
    },

    areaSizes: {
        5: "XPRPG.AreaSize5",
        10: "XPRPG.AreaSize10",
        15: "XPRPG.AreaSize15",
        20: "XPRPG.AreaSize20",
        25: "XPRPG.AreaSize25",
        30: "XPRPG.AreaSize30",
        40: "XPRPG.AreaSize40",
        45: "XPRPG.AreaSize45",
        50: "XPRPG.AreaSize50",
        60: "XPRPG.AreaSize60",
        65: "XPRPG.AreaSize65",
        75: "XPRPG.AreaSize75",
        80: "XPRPG.AreaSize80",
        90: "XPRPG.AreaSize90",
        100: "XPRPG.AreaSize100",
        120: "XPRPG.AreaSize120",
        360: "XPRPG.AreaSize360",
        500: "XPRPG.AreaSize500",
        1000: "XPRPG.AreaSize1000",
        1320: "XPRPG.AreaSizeQuarterMile",
        5280: "XPRPG.AreaSize1Mile",
    },

    alignments,
    alignmentTraits,

    attitude: {
        hostile: "XPRPG.Attitudes.Hostile",
        unfriendly: "XPRPG.Attitudes.Unfriendly",
        indifferent: "XPRPG.Attitudes.Indifferent",
        friendly: "XPRPG.Attitudes.Friendly",
        helpful: "XPRPG.Attitudes.Helpful",
    },

    skillList: {
        acrobatics: "XPRPG.SkillAcrobatics",
        arcana: "XPRPG.SkillArcana",
        athletics: "XPRPG.SkillAthletics",
        crafting: "XPRPG.SkillCrafting",
        deception: "XPRPG.SkillDeception",
        diplomacy: "XPRPG.SkillDiplomacy",
        intimidation: "XPRPG.SkillIntimidation",
        medicine: "XPRPG.SkillMedicine",
        nature: "XPRPG.SkillNature",
        occultism: "XPRPG.SkillOccultism",
        performance: "XPRPG.SkillPerformance",
        religion: "XPRPG.SkillReligion",
        society: "XPRPG.SkillSociety",
        stealth: "XPRPG.SkillStealth",
        survival: "XPRPG.SkillSurvival",
        thievery: "XPRPG.SkillThievery",
        lore: "XPRPG.SkillLore",
    },

    spellComponents: {
        V: "XPRPG.SpellComponentV",
        S: "XPRPG.SpellComponentS",
        M: "XPRPG.SpellComponentM",
        F: "XPRPG.SpellComponentF",
    },

    spellCategories: {
        spell: "XPRPG.SpellCategorySpell",
        focus: "XPRPG.SpellCategoryFocus",
        ritual: "XPRPG.SpellCategoryRitual",
    },

    spellTypes: {
        attack: "XPRPG.SpellTypeAttack",
        save: "XPRPG.SpellTypeSave",
        heal: "XPRPG.SpellTypeHeal",
        utility: "XPRPG.SpellTypeUtility",
    },

    spellLevels: {
        1: "XPRPG.SpellLevel1",
        2: "XPRPG.SpellLevel2",
        3: "XPRPG.SpellLevel3",
        4: "XPRPG.SpellLevel4",
        5: "XPRPG.SpellLevel5",
        6: "XPRPG.SpellLevel6",
        7: "XPRPG.SpellLevel7",
        8: "XPRPG.SpellLevel8",
        9: "XPRPG.SpellLevel9",
        10: "XPRPG.SpellLevel10",
    }, // TODO: Compute levels!

    featTypes,

    actionTypes: {
        action: "XPRPG.ActionTypeAction",
        reaction: "XPRPG.ActionTypeReaction",
        free: "XPRPG.ActionTypeFree",
        passive: "XPRPG.ActionTypePassive",
    },

    actionsNumber: {
        1: "XPRPG.ActionNumber1",
        2: "XPRPG.ActionNumber2",
        3: "XPRPG.ActionNumber3",
    },

    actionCategories: {
        interaction: "XPRPG.ActionCategoryInteraction",
        defensive: "XPRPG.ActionCategoryDefensive",
        offensive: "XPRPG.ActionCategoryOffensive",
    },

    frequencies: {
        PT1M: "XPRPG.Duration.PT1M",
        PT10M: "XPRPG.Duration.PT10M",
        PT1H: "XPRPG.Duration.PT1H",
        PT24H: "XPRPG.Duration.PT24H",
        day: "XPRPG.Duration.day",
        P1W: "XPRPG.Duration.P1W",
    },

    timeUnits: {
        rounds: "XPRPG.Time.Unit.Rounds",
        minutes: "XPRPG.Time.Unit.Minutes",
        hours: "XPRPG.Time.Unit.Hours",
        days: "XPRPG.Time.Unit.Days",
        unlimited: "XPRPG.Time.Unit.Unlimited",
        encounter: "XPRPG.Time.Unit.UntilEncounterEnds",
    },

    // Proficiency Multipliers
    proficiencyLevels: [
        "XPRPG.ProficiencyLevel0", // untrained
        "XPRPG.ProficiencyLevel1", // trained
        "XPRPG.ProficiencyLevel2", // expert
        "XPRPG.ProficiencyLevel3", // master
        "XPRPG.ProficiencyLevel4", // legendary
    ] as const,

    actorSizes: sizeTypes,

    actorTypes,

    speedTypes: {
        swim: "XPRPG.SpeedTypesSwim",
        climb: "XPRPG.SpeedTypesClimb",
        fly: "XPRPG.SpeedTypesFly",
        burrow: "XPRPG.SpeedTypesBurrow",
    },

    prerequisitePlaceholders: {
        prerequisite1: "XPRPG.Prerequisite1",
        prerequisite2: "XPRPG.Prerequisite2",
        prerequisite3: "XPRPG.Prerequisite3",
        prerequisite4: "XPRPG.Prerequisite4",
        prerequisite5: "XPRPG.Prerequisite5",
    },

    senses,

    senseAcuity,

    bulkTypes: {
        L: "XPRPG.BulkTypeLight",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
        16: "16",
        17: "17",
        18: "18",
        19: "19",
        20: "20",
        21: "21",
        22: "22",
        23: "23",
        24: "24",
        25: "25",
        26: "26",
        27: "27",
        28: "28",
        29: "29",
        30: "30",
        31: "31",
        32: "32",
        33: "33",
        34: "34",
        35: "35",
        36: "36",
        37: "37",
        38: "38",
        39: "39",
        40: "40",
        41: "41",
        42: "42",
        43: "43",
        44: "44",
        45: "45",
        46: "46",
        47: "47",
        48: "48",
        49: "49",
        50: "50",
    },

    conditionTypes,

    xpsFactions: {
        EA: "XPRPG.PFS.Factions.EA",
        GA: "XPRPG.PFS.Factions.GA",
        HH: "XPRPG.PFS.Factions.HH",
        VS: "XPRPG.PFS.Factions.VS",
        RO: "XPRPG.PFS.Factions.RO",
        VW: "XPRPG.PFS.Factions.VW",
    },

    xpsSchools: {
        none: "XPRPG.PFS.School.None",
        scrolls: "XPRPG.PFS.School.Scrolls",
        spells: "XPRPG.PFS.School.Spells",
        swords: "XPRPG.PFS.School.Swords",
    },

    immunityTypes,

    // Languages, alphabetical by common, uncommon, secret
    languages: {
        common: "XPRPG.LanguageCommon",
        draconic: "XPRPG.LanguageDraconic",
        dwarven: "XPRPG.LanguageDwarven",
        elven: "XPRPG.LanguageElven",
        gnomish: "XPRPG.LanguageGnomish",
        goblin: "XPRPG.LanguageGoblin",
        halfling: "XPRPG.LanguageHalfling",
        jotun: "XPRPG.LanguageJotun",
        orcish: "XPRPG.LanguageOrcish",
        sylvan: "XPRPG.LanguageSylvan",
        undercommon: "XPRPG.LanguageUndercommon",
        ysoki: "XPRPG.LanguageYsoki",
        abyssal: "XPRPG.LanguageAbyssal",
        adlet: "XPRPG.LanguageAdlet",
        aklo: "XPRPG.LanguageAklo",
        akitonian: "XPRPG.LanguageAkitonian",
        alghollthu: "XPRPG.LanguageAlghollthu",
        amurrun: "XPRPG.LanguageAmurrun",
        anadi: "XPRPG.LanguageAnadi",
        "ancient-osiriani": "XPRPG.LanguageAncientOsiriani",
        anugobu: "XPRPG.LanguageAnugobu",
        arcadian: "XPRPG.LanguageArcadian",
        aquan: "XPRPG.LanguageAquan",
        arboreal: "XPRPG.LanguageArboreal",
        auran: "XPRPG.LanguageAuran",
        boggard: "XPRPG.LanguageBoggard",
        calda: "XPRPG.LanguageCalda",
        caligni: "XPRPG.LanguageCaligni",
        celestial: "XPRPG.LanguageCelestial",
        cyclops: "XPRPG.LanguageCyclops",
        daemonic: "XPRPG.LanguageDaemonic",
        destrachan: "XPRPG.LanguageDestrachan",
        drooni: "XPRPG.LanguageDrooni",
        dziriak: "XPRPG.LanguageDziriak",
        ekujae: "XPRPG.LanguageEkujae",
        erutaki: "XPRPG.LanguageErutaki",
        formian: "XPRPG.LanguageFormian",
        garundi: "XPRPG.LanguageGarundi",
        girtablilu: "XPRPG.LanguageGirtablilu",
        gnoll: "XPRPG.LanguageGnoll",
        goloma: "XPRPG.LanguageGoloma",
        grippli: "XPRPG.LanguageGrippli",
        hallit: "XPRPG.LanguageHallit",
        hwan: "XPRPG.LanguageHwan",
        iblydan: "XPRPG.LanguageIblydan",
        ignan: "XPRPG.LanguageIgnan",
        ikeshti: "XPRPG.LanguageIkeshti",
        immolis: "XPRPG.LanguageImmolis",
        infernal: "XPRPG.LanguageInfernal",
        iruxi: "XPRPG.LanguageIruxi",
        jistkan: "XPRPG.LanguageJistkan",
        jyoti: "XPRPG.LanguageJyoti",
        kaava: "XPRPG.LanguageKaava",
        kashrishi: "XPRPG.LanguageKashrishi",
        kibwani: "XPRPG.LanguageKibwani",
        kitsune: "XPRPG.LanguageKitsune",
        kelish: "XPRPG.LanguageKelish",
        lirgeni: "XPRPG.LanguageLirgeni",
        mahwek: "XPRPG.LanguageMahwek",
        minaten: "XPRPG.LanguageMinaten",
        minkaian: "XPRPG.LanguageMinkaian",
        mwangi: "XPRPG.LanguageMwangi",
        mzunu: "XPRPG.LanguageMzunu",
        nagaji: "XPRPG.LanguageNagaji",
        necril: "XPRPG.LanguageNecril",
        ocotan: "XPRPG.LanguageOcotan",
        okaiyan: "XPRPG.LanguageOkaiyan",
        osiriani: "XPRPG.LanguageOsiriani",
        protean: "XPRPG.LanguageProtean",
        rasu: "XPRPG.LanguageRasu",
        ratajin: "XPRPG.LanguageRatajin",
        razatlani: "XPRPG.LanguageRazatlani",
        requian: "XPRPG.LanguageRequian",
        russian: "XPRPG.LanguageRussian",
        senzar: "XPRPG.LanguageSenzar",
        shadowtongue: "XPRPG.LanguageShadowtongue",
        shobhad: "XPRPG.LanguageShobhad",
        shisk: "XPRPG.LanguageShisk",
        shoanti: "XPRPG.LanguageShoanti",
        shoony: "XPRPG.LanguageShoony",
        skald: "XPRPG.LanguageSkald",
        sphinx: "XPRPG.LanguageSphinx",
        strix: "XPRPG.LanguageStrix",
        taldane: "XPRPG.LanguageTaldane",
        tekritanin: "XPRPG.LanguageTekritanin",
        tengu: "XPRPG.LanguageTengu",
        terran: "XPRPG.LanguageTerran",
        thassilonian: "XPRPG.LanguageThassilonian",
        tien: "XPRPG.LanguageTien",
        utopian: "XPRPG.LanguageUtopian",
        vanara: "XPRPG.LanguageVanara",
        varisian: "XPRPG.LanguageVarisian",
        varki: "XPRPG.LanguageVarki",
        vishkanyan: "XPRPG.LanguageVishkanyan",
        vudrani: "XPRPG.LanguageVudrani",
        wyrwood: "XPRPG.LanguageWyrwood",
        xanmba: "XPRPG.LanguageXanmba",
        androffan: "XPRPG.LanguageAndroffan",
        azlanti: "XPRPG.LanguageAzlanti",
        grioth: "XPRPG.LanguageGrioth",
        kovintal: "XPRPG.LanguageKovintal",
        migo: "XPRPG.LanguageMiGo",
        munavri: "XPRPG.LanguageMunavri",
        samsaran: "XPRPG.LanguageSamsaran",
        sasquatch: "XPRPG.LanguageSasquatch",
        shae: "XPRPG.LanguageShae",
        yithian: "XPRPG.LanguageYithian",
        druidic: "XPRPG.LanguageDruidic",
    },

    attackEffects: {
        grab: "XPRPG.AttackEffectGrab",
        "improved-grab": "XPRPG.AttackEffectImprovedGrab",
        constrict: "XPRPG.AttackEffectConstrict",
        "greater-constrict": "XPRPG.AttackEffectGreaterConstrict",
        knockdown: "XPRPG.AttackEffectKnockdown",
        "improved-knockdown": "XPRPG.AttackEffectImprovedKnockdown",
        push: "XPRPG.AttackEffectPush",
        "improved-push": "XPRPG.AttackEffectImprovedPush",
        trip: "XPRPG.AttackEffectTrip",
    },

    // Year offsets relative to the current actual year
    worldClock: {
        AR: { yearOffset: 2700 },
        IC: { yearOffset: 5200 },
        AD: { yearOffset: -95 },
        CE: { yearOffset: 0 },
    },

    runes: {
        weapon: {
            property: { ...WEAPON_PROPERTY_RUNES },
        },
    },

    SETTINGS: {
        automation: {
            rulesBasedVision: {
                name: "XPRPG.SETTINGS.Automation.RulesBasedVision.Name",
                hint: "XPRPG.SETTINGS.Automation.RulesBasedVision.Hint",
            },
            iwr: {
                name: "XPRPG.SETTINGS.Automation.IWR.Name",
                hint: "XPRPG.SETTINGS.Automation.IWR.Hint",
            },
            effectExpiration: {
                name: "XPRPG.SETTINGS.Automation.EffectExpiration.Name",
                hint: "XPRPG.SETTINGS.Automation.EffectExpiration.Hint",
            },
            removeExpiredEffects: {
                name: "XPRPG.SETTINGS.Automation.RemoveExpiredEffects.Name",
                hint: "XPRPG.SETTINGS.Automation.RemoveExpiredEffects.Hint",
            },
            flankingDetection: {
                name: "XPRPG.SETTINGS.Automation.FlankingDetection.Name",
                hint: "XPRPG.SETTINGS.Automation.FlankingDetection.Hint",
            },
            actorsDeadAtZero: {
                name: "XPRPG.SETTINGS.Automation.ActorsDeadAtZero.Name",
                hint: "XPRPG.SETTINGS.Automation.ActorsDeadAtZero.Hint",
                neither: "XPRPG.SETTINGS.Automation.ActorsDeadAtZero.Neither",
                npcsOnly: "XPRPG.SETTINGS.Automation.ActorsDeadAtZero.NPCsOnly",
                pcsOnly: "XPRPG.SETTINGS.Automation.ActorsDeadAtZero.PCsOnly",
                both: "XPRPG.SETTINGS.Automation.ActorsDeadAtZero.Both",
            },
            lootableNPCs: {
                name: "XPRPG.SETTINGS.Automation.LootableNPCs.Name",
                hint: "XPRPG.SETTINGS.Automation.LootableNPCs.Hint",
            },
        },
        homebrew: {
            creatureTraits: {
                name: "XPRPG.SETTINGS.Homebrew.CreatureTraits.Name",
                hint: "XPRPG.SETTINGS.Homebrew.CreatureTraits.Hint",
            },
            featTraits: {
                name: "XPRPG.SETTINGS.Homebrew.FeatTraits.Name",
                hint: "XPRPG.SETTINGS.Homebrew.FeatTraits.Hint",
            },
            languages: {
                name: "XPRPG.SETTINGS.Homebrew.Languages.Name",
                hint: "XPRPG.SETTINGS.Homebrew.Languages.Hint",
            },
            magicSchools: {
                name: "XPRPG.SETTINGS.Homebrew.MagicSchools.Name",
                hint: "XPRPG.SETTINGS.Homebrew.MagicSchools.Hint",
            },
            spellTraits: {
                name: "XPRPG.SETTINGS.Homebrew.SpellTraits.Name",
                hint: "XPRPG.SETTINGS.Homebrew.SpellTraits.Hint",
            },
            weaponCategories: {
                name: "XPRPG.SETTINGS.Homebrew.WeaponCategories.Name",
                hint: "XPRPG.SETTINGS.Homebrew.WeaponCategories.Hint",
            },
            weaponGroups: {
                name: "XPRPG.SETTINGS.Homebrew.WeaponGroups.Name",
                hint: "XPRPG.SETTINGS.Homebrew.WeaponGroups.Hint",
            },
            baseWeapons: {
                name: "XPRPG.SETTINGS.Homebrew.BaseWeapons.Name",
                hint: "XPRPG.SETTINGS.Homebrew.BaseWeapons.Hint",
            },
            weaponTraits: {
                name: "XPRPG.SETTINGS.Homebrew.WeaponTraits.Name",
                hint: "XPRPG.SETTINGS.Homebrew.WeaponTraits.Hint",
            },
            equipmentTraits: {
                name: "XPRPG.SETTINGS.Homebrew.EquipmentTraits.Name",
                hint: "XPRPG.SETTINGS.Homebrew.EquipmentTraits.Hint",
            },
        },
        worldClock: {
            name: "XPRPG.SETTINGS.WorldClock.Name",
            label: "XPRPG.SETTINGS.WorldClock.Label",
            hint: "XPRPG.SETTINGS.WorldClock.Hint",
            dateTheme: {
                name: "XPRPG.SETTINGS.WorldClock.DateTheme.Name",
                hint: "XPRPG.SETTINGS.WorldClock.DateTheme.Hint",
                AR: "XPRPG.SETTINGS.WorldClock.DateTheme.AR",
                AD: "XPRPG.SETTINGS.WorldClock.DateTheme.AD",
                CE: "XPRPG.SETTINGS.WorldClock.DateTheme.CE",
            },
            timeConvention: {
                name: "XPRPG.SETTINGS.WorldClock.TimeConvention.Name",
                hint: "XPRPG.SETTINGS.WorldClock.TimeConvention.Hint",
                twentyFour: "XPRPG.SETTINGS.WorldClock.TimeConvention.TwentyFour",
                twelve: "XPRPG.SETTINGS.WorldClock.TimeConvention.Twelve",
            },
            showClockButton: {
                name: "XPRPG.SETTINGS.WorldClock.ShowClockButton.Name",
                hint: "XPRPG.SETTINGS.WorldClock.ShowClockButton.Hint",
            },
            playersCanView: {
                name: "XPRPG.SETTINGS.WorldClock.PlayersCanView.Name",
                hint: "XPRPG.SETTINGS.WorldClock.PlayersCanView.Hint",
            },
            syncDarkness: {
                name: "XPRPG.SETTINGS.WorldClock.SyncDarkness.Name",
                hint: "XPRPG.SETTINGS.WorldClock.SyncDarkness.Hint",
            },
            syncDarknessScene: {
                name: "XPRPG.SETTINGS.WorldClock.SyncDarknessScene.Name",
                hint: "XPRPG.SETTINGS.WorldClock.SyncDarknessScene.Hint",
                enabled: "XPRPG.SETTINGS.WorldClock.SyncDarknessScene.Enabled",
                disabled: "XPRPG.SETTINGS.WorldClock.SyncDarknessScene.Disabled",
                default: "XPRPG.SETTINGS.WorldClock.SyncDarknessScene.Default",
            },
            worldCreatedOn: {
                name: "XPRPG.SETTINGS.WorldClock.WorldCreatedOn.Name",
                hint: "XPRPG.SETTINGS.WorldClock.WorldCreatedOn.Hint",
            },
        },
        CampaignFeats: {
            name: "XPRPG.SETTINGS.CampaignFeats.Name",
            hint: "XPRPG.SETTINGS.CampaignFeats.Hint",
        },
    },

    Actor: {
        documentClasses: {
            character: CharacterXPRPG,
            npc: NPCXPRPG,
            hazard: HazardXPRPG,
            loot: LootXPRPG,
            familiar: FamiliarXPRPG,
            party: PartyXPRPG,
            vehicle: VehicleXPRPG,
        },
    },

    Item: {
        documentClasses: {
            action: ActionItemXPRPG,
            affliction: AfflictionXPRPG,
            ancestry: AncestryXPRPG,
            armor: ArmorXPRPG,
            background: BackgroundXPRPG,
            backpack: ContainerXPRPG,
            book: BookXPRPG,
            class: ClassXPRPG,
            condition: ConditionXPRPG,
            consumable: ConsumableXPRPG,
            deity: DeityXPRPG,
            effect: EffectXPRPG,
            equipment: EquipmentXPRPG,
            feat: FeatXPRPG,
            heritage: HeritageXPRPG,
            kit: KitXPRPG,
            lore: LoreXPRPG,
            melee: MeleeXPRPG,
            spell: SpellXPRPG,
            spellcastingEntry: SpellcastingEntryXPRPG,
            treasure: TreasureXPRPG,
            weapon: WeaponXPRPG,
        },
        traits: {
            action: actionTraits,
            affliction: actionTraits,
            armor: armorTraits,
            ancestry: creatureTraits,
            backpack: equipmentTraits,
            book: equipmentTraits,
            consumable: consumableTraits,
            equipment: equipmentTraits,
            feat: featTraits,
            heritage: featTraits,
            kit: classTraits,
            melee: npcAttackTraits,
            spell: spellTraits,
            weapon: weaponTraits,
        },
    },

    JournalEntry: { sheetClass: JournalSheetXPRPG },

    Canvas: {
        darkness: {
            default: CONFIG.Canvas.darknessColor,
            gmVision: 0x908cb9,
        },
    },
};
